Iskowela/SrSeA/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from chatbot import views as chatbot_views
from information import views as information_views
from markers import views as markers_views
from ssr import views as ssr_views
from users import views as user_views
from main import views as main_views
from portal import views as portal_views
from analytics import views as analytics_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from .decorators import toggle_required

urlpatterns = [
    path('', portal_views.SchoolListView.as_view(), name="portal"),
    path('search/', portal_views.SchoolSearchListView.as_view(), name='search'),
	path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', login_required(auth_views.LogoutView.as_view(template_name='users/logout.html', next_page=reverse_lazy('portal'))), name='logout'),
 #Signed in only

    path('register/', user_views.register, name='register'), #Link to (create new admin)
    path('<int:profile_id>/profile/', user_views.profile, name='profile'),
    path('<int:profile_id>/pupdate/', login_required(user_views.pupdate), name='pupdate'), #Admin only


    # ---------------------------------------------------------------------------------
    path('<int:profile_id>/processguides/', toggle_required(information_views.processguide_list, "processguides_toggle"), name='processguides'),
    path('<int:profile_id>/courses/', toggle_required(information_views.course_list, "courses_toggle"), name='courses'),
    path('<int:profile_id>/scholarships/', toggle_required(information_views.scholarship_list, "scholarships_toggle"), name='scholarships'),

    path('<int:profile_id>/processguides/new', login_required(information_views.ProcessGuidesCreateView.as_view()), name='processguide-create'),
    path('<int:profile_id>/courses/new', login_required(information_views.CoursesCreateView.as_view()), name='courses-create'),
    path('<int:profile_id>/scholarships/new', login_required(information_views.ScholarshipsCreateView.as_view()), name='scholarship-create'),

    path('<int:profile_id>/processguides/update/<pk>/', login_required(information_views.ProcessGuidesUpdateView.as_view()), name='processguide-update'),
    path('<int:profile_id>/courses/update/<pk>/', login_required(information_views.CoursesUpdateView.as_view()), name='courses-update'),
    path('<int:profile_id>/scholarships/update/<pk>/', login_required(information_views.ScholarshipsUpdateView.as_view()), name='scholarship-update'),

    path('<int:profile_id>/processguides/delete/<pk>/', login_required(information_views.ProcessGuidesDeleteView.as_view()), name='processguide-delete'),
    path('<int:profile_id>/courses/delete/<pk>/', login_required(information_views.CoursesDeleteView.as_view()), name='courses-delete'),
    path('<int:profile_id>/scholarships/delete/<pk>/', login_required(information_views.ScholarshipsDeleteView.as_view()), name='scholarship-delete'),

    # ---------------------------------------------------------------------------------
    path('<int:profile_id>/markers/<int:mtype>', toggle_required(markers_views.markers, "markers_toggle"), name='markers'),

    path('<int:profile_id>/markers/new-event', markers_views.EventCreateView.as_view(), name='event-create'),
    path('<int:profile_id>/markers/new-place', markers_views.PlaceCreateView.as_view(), name='place-create'),
    path('<int:profile_id>/markers/suggest-event', markers_views.SuggestEventCreateView.as_view(), name='suggest-event'),
    path('<int:profile_id>/markers/suggest-place', markers_views.SuggestPlaceCreateView.as_view(), name='suggest-place'),

    path('<int:profile_id>/markers/2/<int:pk>/update/', markers_views.PlaceUpdateView.as_view(), name='place-update'),
    path('<int:profile_id>/markers/1/<int:pk>/update/', markers_views.EventUpdateView.as_view(), name='event-update'),
    # path('markers/3/<int:pk>/update/', markers_views.SuggestEventUpdateView.as_view(), name='suggest-event-update'),
    # path('markers/4/<int:pk>/update/', markers_views.SuggestPlaceUpdateView.as_view(), name='suggest-place-update'),

    path('<int:profile_id>/markers/2/<int:pk>/delete/', markers_views.PlaceDeleteView.as_view(), name='place-delete'),
    path('<int:profile_id>/markers/1/<int:pk>/delete/', markers_views.EventDeleteView.as_view(), name='event-delete'),
    path('<int:profile_id>/markers/3/<int:pk>/delete/', markers_views.SuggestEventDeleteView.as_view(), name='suggest-event-delete'),
    path('<int:profile_id>/markers/4/<int:pk>/delete/', markers_views.SuggestPlaceDeleteView.as_view(), name='suggest-place-delete'),

    # ---------------------------------------------------------------------------------
    # path('<int:profile_id>/chatbot/', chatbot_views.index, name='chatbot-index'),
    path('<int:profile_id>/chatbot/', toggle_required(chatbot_views.chatbot, "chatbot_toggle"), name='chatbot'),
    path('<int:profile_id>/send/', chatbot_views.send, name='send'),
    path('getMessages/<int:user_id>/', chatbot_views.getMessages, name='getMessages'),

    path('<int:profile_id>/settings/<int:pk>', login_required(main_views.SettingsUpdateView.as_view()), name='settings'), 

    # ---------------------------------------------------------------------------------
    path('<int:profile_id>/ssr/', login_required(ssr_views.SSRListView.as_view()), name='ssr-index'), #Admin only
    path('<int:profile_id>/ssr/new', ssr_views.SSRCreateView.as_view(), name='ssr-create'),
    path('<int:profile_id>/ssr/<int:pk>/delete/', login_required(ssr_views.SSRDeleteView.as_view()), name='ssr-delete'), #Admin only

    path('<int:profile_id>/analytics/', toggle_required(analytics_views.traffic_monitor, "web_analytics_toggle"), name="analytics"),
    #path('<int:profile_id>/analytics/monitor/', , name="analytics-monitor"), 

    path('queryScholarships/<int:school_id>/', chatbot_views.queryScholarships, name='queryScholarships'),
    path('queryScholarships/<int:school_id>/<str:scholarship_name>/', chatbot_views.queryScholarships, name='queryScholarships'),
    path('queryCourses/<int:school_id>/', chatbot_views.queryCourses, name='queryCourses'),
    path('queryCourses/<int:school_id>/<str:college_group>/', chatbot_views.queryCourses, name='queryCourses'),
    path('queryProcessGuides/<int:school_id>/', chatbot_views.queryProcessGuides, name='queryProcessGuides'),
    path('queryProcessGuides/<int:school_id>/<str:process_name>/', chatbot_views.queryProcessGuides, name='queryProcessGuides'),
    path('queryProcessGuides/<int:school_id>/<int:apply>/', chatbot_views.queryProcessGuides, name='queryProcessGuides'),
    path('queryPlaces/<int:school_id>/', chatbot_views.queryPlaces, name='queryPlaces'),
    path('queryPlaces/<int:school_id>/<str:place_name>/', chatbot_views.queryPlaces, name='queryPlaces'),
    path('queryPlacesByType/<int:school_id>/<str:place_type>/', chatbot_views.queryPlacesByType, name='queryPlacesByType'),
    path('queryEvents/<int:school_id>/', chatbot_views.queryEvents, name='queryEvents'),
    path('queryEvents/<int:school_id>/<str:event_name>/', chatbot_views.queryEvents, name='queryEvents'),
    path('update-time-spent/', analytics_views.update_time_spent, name='update_time_spent'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Iskowela/main/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('<int:profile_id>', views.index, name='main-index'),
    path('main_update', views.main_update, name='main-update'),
    path('<int:profile_id>/post/new', login_required(views.PostCreateView.as_view()), name='post-create'),
    path('<int:profile_id>/post/delete/<pk>/', login_required(views.PostDeleteView.as_view()), name='post-delete'),
    path('<int:profile_id>/post/update/<pk>/', login_required(views.PostUpdateView.as_view()), name='post-update'),
]

Iskowela/markers/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from users.models import Profile

class Event_Markers(models.Model):
	class EventType(models.IntegerChoices):
		OFFLINE = 1
		ONLINE = 2
		
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE, default=1)
	name = models.CharField(max_length=100)
	type = models.IntegerField(choices=EventType.choices)
	description = models.CharField(max_length=100, default='')
	event_date = models.DateTimeField()
	longitude = models.DecimalField(default=0, decimal_places=20, max_digits=25)
	latitude = models.DecimalField(default=0, decimal_places=20, max_digits=25)
	last_updated = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('markers', args=[self.profile.id, 1])


class Place_Markers(models.Model):
	class PlaceType(models.IntegerChoices):
		HEALTH = 1
		FOOD = 2
		FINANCE = 3
		STORE = 4
		ETC = 5
	
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE, default=1)
	name = models.CharField(max_length=100)
	type = models.IntegerField(choices=PlaceType.choices)
	description = models.CharField(max_length=100, default='')
	longitude = models.DecimalField(default=0, decimal_places=20, max_digits=25)
	latitude = models.DecimalField(default=0, decimal_places=20, max_digits=25)
	last_updated = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.name
	
	def get_absolute_url(self):
		return reverse('markers', args=[self.profile.id, 2])

class Event_Suggestions(models.Model):
	class EventType(models.IntegerChoices):
		OFFLINE = 1
		ONLINE = 2
	class Action(models.IntegerChoices):
		CREATE = 1
		UPDATE = 2
		DELETE = 3
		
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE, default=1)
	event_marker = models.ForeignKey(Event_Markers, on_delete=models.CASCADE, null=True, blank=True)
	name = models.CharField(max_length=100, null=True, blank=True)
	type = models.IntegerField(choices=EventType.choices, null=True, blank=True)
	description = models.CharField(max_length=100, default='')
	event_date = models.DateTimeField(null=True, blank=True)
	cud = models.IntegerField(choices=Action.choices)
	longitude = models.DecimalField(default=0, decimal_places=20, max_digits=25, null=True, blank=True)
	latitude = models.DecimalField(default=0, decimal_places=20, max_digits=25, null=True, blank=True)
	date_posted = models.DateTimeField(default=timezone.now)
	
	def __str__(self):
		if self.name:
			return self.name
		else:
			return self.event_marker.name
			
	def get_absolute_url(self):
		return reverse('markers', args=[self.profile.id, 1])

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		if self.event_marker is not None:
			self.name = self.event_marker.name
			if self.cud == 3:
				self.type = self.event_marker.type
				self.event_date = self.event_marker.event_date
				self.longitude = self.event_marker.longitude
				self.latitude = self.event_marker.latitude

class Place_Suggestions(models.Model):
	class PlaceType(models.IntegerChoices):
		HEALTH = 1
		FOOD = 2
		FINANCE = 3
		STORE = 4
		ETC = 5
	class Action(models.IntegerChoices):
		CREATE = 1
		UPDATE = 2
		DELETE = 3
		
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE, default=1)
	place_marker = models.ForeignKey(Place_Markers, on_delete=models.CASCADE, null=True, blank=True)
	name = models.CharField(max_length=100, null=True, blank=True)
	type = models.IntegerField(choices=PlaceType.choices, null=True, blank=True)
	description = models.CharField(max_length=100, default='')
	cud = models.IntegerField(choices=Action.choices)
	longitude = models.DecimalField(default=0, decimal_places=20, max_digits=25, null=True, blank=True)
	latitude = models.DecimalField(default=0, decimal_places=20, max_digits=25, null=True, blank=True)
	date_posted = models.DateTimeField(default=timezone.now)
	
	def __str__(self):
		if self.name:
			return self.name
		else:
			return self.place_marker.name

	def get_absolute_url(self):
		return reverse('markers', args=[self.profile.id, 2])

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		if self.place_marker is not None:
			self.name = self.place_marker.name
			if self.cud == 3:
				self.type = self.place_marker.type
				self.longitude = self.place_marker.longitude
				self.latitude = self.place_marker.latitude

Iskowela/markers/templates/markers/event_markers_confirm_delete.html
{% extends "main/base.html" %}
{% block content %}

<div class="container">
	<div class="infoform">
		<form method="POST">
			{% csrf_token %}
            <div class="d-flex border-bottom pb-4">
                <h2>Deleting {{object.name}}</h2>
            </div>
			<div class="pt-4">
				Are you sure you want to delete this marker? 
				<br><br>
				Please note that this action <b style="color: #F9594A;">cannot be reverted</b>.</div>
            <div class="mt-4 d-flex">
                <input type="submit" value="Delete Marker" class="btn neg-btn mr-3"> 
                <a class="btn add-btn" href="{% url 'markers' profile_id 1 %}">Cancel</a>
            </div>
		</form>
	</div>
</div>

{% endblock content %}

Iskowela/markers/templates/markers/event_markers_form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<script src="https://api.tiles.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
<link href="https://api.tiles.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css" rel="stylesheet"/>

<style>
	.map {
		height: 500px;
	}
	#info {
		display: table;
		position: relative;
		margin: 0px auto;
		word-wrap: anywhere;
		white-space: pre-wrap;
		padding: 10px;
		border: none;
		border-radius: 3px;
		font-size: 12px;
		text-align: center;
		color: #222;
		background: #fff;
	}
</style>

<div class="container">
	<div class="infoform mb-5">
		<form method="POST">
			{% csrf_token %}
			<div class="d-flex border-bottom pb-4">
                <a href="{% url 'markers' profile_id 1 %}" class="mr-3 align-self-center" style="color: black;"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                </svg></a>
                {% if object.name != None %}
                    <h2>Updating "{{ object.name }}"</h2>
                {% else %}
                    <h2>Add Event</h2>
                {% endif %}
           </div>
			<fieldset class="form-group pt-4">
				{{ form | crispy }}
			</fieldset>
			<div id="map" class="map mb-3"></div>
			<pre id="info"></pre>
            <div class="mt-4 d-flex">
				<button class="btn add-btn mr-auto" type="submit">Post</button>
                <a class="btn neg-btn" href="{% url 'markers' profile_id 1 %}">Cancel</a>
			</div>
		</form>
	</div>
</div>

<script>
	mapboxgl.accessToken = 'pk.eyJ1Ijoiamx0c2FuZyIsImEiOiJjbGVpODE2bDAwdzh1M3ZsZGVyM2RwM3NkIn0.tqAoS6z_fUkuy6BTdA3XJA';
	/**
	* Add the map to the page
	*/
	const map = new mapboxgl.Map({
		container: 'map',
		style: 'mapbox://styles/mapbox/streets-v12',
		center: [{{ active_profile.longitude }}, {{ active_profile.latitude }}],
		zoom: 18,
		pitch: 40,
		bearing: 20,
		antialias: true,
	});

	map.addControl(new mapboxgl.ScaleControl({maxWidth:100}));

	map.on('mousemove', (e) => {
		document.getElementById('info').innerHTML =
		// `e.point` is the x, y coordinates of the `mousemove` event
		// relative to the top-left corner of the map.
		JSON.stringify(e.point) +
		'<br />' +
		// `e.lngLat` is the longitude, latitude geographical position of the event.
		JSON.stringify(e.lngLat.wrap());
	});

	const lng = document.getElementById('id_longitude');
	const lat = document.getElementById('id_latitude');
	
	var marker = new mapboxgl.Marker().setLngLat([lng.value, lat.value]).addTo(map);

	function add_marker (e) {
		var coordinates = e.lngLat;
		lng.value = coordinates.lng;
		lat.value = coordinates.lat;
		console.log('Lng:', coordinates.lng, 'Lat:', coordinates.lat);
		marker.setLngLat(coordinates).addTo(map);

	}

	map.on('click', add_marker);

</script>

{% endblock content %}

Iskowela/markers/templates/markers/event_suggestions_confirm_delete.html
{% extends "main/base.html" %}
{% block content %}

<div class="container">
	<div class="infoform">
		<form method="POST">
			{% csrf_token %}
            <div class="d-flex border-bottom pb-4">
                <h2>Deleting {{object.name}}</h2>
            </div>
			<div class="pt-4">
				Are you sure you want to delete this suggestion? 
				<br><br>
				Please note that this action <b style="color: #F9594A;">cannot be reverted</b>.</div>
            <div class="mt-4 d-flex">
                <input type="submit" value="Delete" class="btn neg-btn mr-3"> 
                <a class="btn add-btn" href="{% url 'markers' profile_id 3 %}">Cancel</a>
            </div>
		</form>
	</div>
</div>

{% endblock content %}

Iskowela/markers/templates/markers/event_suggestions_form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<script src="https://api.tiles.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
<link href="https://api.tiles.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css" rel="stylesheet"/>

<style>
	.map {
		height: 500px;
	}
	#info {
		display: table;
		position: relative;
		margin: 0px auto;
		word-wrap: anywhere;
		white-space: pre-wrap;
		padding: 10px;
		border: none;
		border-radius: 3px;
		font-size: 12px;
		text-align: center;
		color: #222;
		background: #fff;
	}
</style>

<div class="container">
	<div class="infoform mb-5">
		<form method="POST">
			{% csrf_token %}
			<div class="d-flex border-bottom pb-4">
                <a href="{% url 'markers' profile_id 1 %}" class="mr-3 align-self-center" style="color: black;"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                </svg></a>
				<h2>Suggest Event</h2>
            </div>
			<fieldset class="form-group pt-4">
				{{ form | crispy }}
			</fieldset>
			<div id="map" class="map mb-3"></div>
			<pre id="info"></pre>
            <div class="mt-4 d-flex">
				<button class="btn add-btn mr-auto" type="submit">Post</button>
                <a class="btn neg-btn" href="{% url 'markers' profile_id 1 %}">Cancel</a>
			</div>
		</form>
	</div>
</div>

<script>
    const cud_field = document.querySelector('#id_cud');
    const marker_field = document.querySelector('#id_event_marker');
	var label_marker = document.querySelector('label[for="id_event_marker"]');
    const name_field = document.querySelector('#id_name');
	var label_name = document.querySelector('label[for="id_name"]');
    const type_field = document.querySelector('#id_type');
	var label_type = document.querySelector('label[for="id_type"]');
    const date_field = document.querySelector('#id_event_date');
	var label_date = document.querySelector('label[for="id_event_date"]');
    const map_field = document.querySelector('#map');

    function updatePlaceMarkerVisibility() {
        const value = parseInt(cud_field.value);
		marker_field.parentElement.style.display = (value === 2 || value === 3) ? 'block' : 'none';
		label_marker.style.display = (value === 2 || value === 3) ? 'block' : 'none';
		name_field.parentElement.style.display = (value !== 2 && value !== 3) ? 'block' : 'none';
		label_name.style.display = (value !== 2 && value !== 3) ? 'block' : 'none';
		type_field.parentElement.style.display = (value !== 3) ? 'block' : 'none';
		label_type.style.display = (value !== 3) ? 'block' : 'none';
		date_field.parentElement.style.display = (value !== 3) ? 'block' : 'none';
		label_date.style.display = (value !== 3) ? 'block' : 'none';
		map_field.style.display = (value !== 3) ? 'block' : 'none';
    }

	if (cud_field){
		cud_field.addEventListener('change', updatePlaceMarkerVisibility);
		updatePlaceMarkerVisibility();
	}

	mapboxgl.accessToken = 'pk.eyJ1Ijoiamx0c2FuZyIsImEiOiJjbGVpODE2bDAwdzh1M3ZsZGVyM2RwM3NkIn0.tqAoS6z_fUkuy6BTdA3XJA';
	/**
	* Add the map to the page
	*/
	const map = new mapboxgl.Map({
		container: 'map',
		style: 'mapbox://styles/mapbox/streets-v12',
		center: [{{ active_profile.longitude }}, {{ active_profile.latitude }}],
		zoom: 18,
		pitch: 40,
		bearing: 20,
		antialias: true,
	});

	map.addControl(new mapboxgl.ScaleControl({maxWidth:100}));

	map.on('mousemove', (e) => {
		document.getElementById('info').innerHTML =
		// `e.point` is the x, y coordinates of the `mousemove` event
		// relative to the top-left corner of the map.
		JSON.stringify(e.point) +
		'<br />' +
		// `e.lngLat` is the longitude, latitude geographical position of the event.
		JSON.stringify(e.lngLat.wrap());
	});

	const lng = document.getElementById('id_longitude');
	const lat = document.getElementById('id_latitude');

	var marker = new mapboxgl.Marker().setLngLat([lng.value, lat.value]).addTo(map);

	function add_marker (e) {
		var coordinates = e.lngLat;
		lng.value = coordinates.lng;
		lat.value = coordinates.lat;
		console.log('Lng:', coordinates.lng, 'Lat:', coordinates.lat);
		marker.setLngLat(coordinates).addTo(map);

	}

	map.on('click', add_marker);

</script>

{% endblock content %}

Iskowela/markers/templates/markers/place_suggestions_form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<script src="https://api.tiles.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
<link href="https://api.tiles.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css" rel="stylesheet"/>

<style>
	.map {
		height: 500px;
	}
	#info {
		display: table;
		position: relative;
		margin: 0px auto;
		word-wrap: anywhere;
		white-space: pre-wrap;
		padding: 10px;
		border: none;
		border-radius: 3px;
		font-size: 12px;
		text-align: center;
		color: #222;
		background: #fff;
	}
</style>

<div class="container">
	<div class="infoform mb-5">
		<form method="POST">
			{% csrf_token %}
			<div class="d-flex border-bottom pb-4">
                <a href="{% url 'markers' profile_id 2 %}" class="mr-3 align-self-center" style="color: black;"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                  <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                </svg></a>
				<h2>Suggest Place</h2>
            </div>
			<fieldset class="form-group pt-4">
				{{ form | crispy }}
			</fieldset>
			<div id="map" class="map mb-3"></div>
			<pre id="info"></pre>
            <div class="mt-4 d-flex">
				<button class="btn add-btn mr-auto" type="submit">Post</button>
                <a class="btn neg-btn" href="{% url 'markers' profile_id 2 %}">Cancel</a>
			</div>
		</form>
	</div>
</div>

<script>
    const cud_field = document.querySelector('#id_cud');
    const marker_field = document.querySelector('#id_place_marker');
	var label_marker = document.querySelector('label[for="id_place_marker"]');
    const name_field = document.querySelector('#id_name');
	var label_name = document.querySelector('label[for="id_name"]');
    const type_field = document.querySelector('#id_type');
	var label_type = document.querySelector('label[for="id_type"]');
    const map_field = document.querySelector('#map');

    function updatePlaceMarkerVisibility() {
        const value = parseInt(cud_field.value);
		marker_field.parentElement.style.display = (value === 2 || value === 3) ? 'block' : 'none';
		label_marker.style.display = (value === 2 || value === 3) ? 'block' : 'none';
		name_field.parentElement.style.display = (value !== 2 && value !== 3) ? 'block' : 'none';
		label_name.style.display = (value !== 2 && value !== 3) ? 'block' : 'none';
		type_field.parentElement.style.display = (value !== 3) ? 'block' : 'none';
		label_type.style.display = (value !== 3) ? 'block' : 'none';
		map_field.style.display = (value !== 3) ? 'block' : 'none';
    }

	if (cud_field){
		cud_field.addEventListener('change', updatePlaceMarkerVisibility);
		updatePlaceMarkerVisibility();
	}

	mapboxgl.accessToken = 'pk.eyJ1Ijoiamx0c2FuZyIsImEiOiJjbGVpODE2bDAwdzh1M3ZsZGVyM2RwM3NkIn0.tqAoS6z_fUkuy6BTdA3XJA';
	/**
	* Add the map to the page
	*/
	const map = new mapboxgl.Map({
		container: 'map',
		style: 'mapbox://styles/mapbox/streets-v12',
		center: [{{ active_profile.longitude }}, {{ active_profile.latitude }}],
		zoom: 18,
		pitch: 40,
		bearing: 20,
		antialias: true,
	});

	map.addControl(new mapboxgl.ScaleControl({maxWidth:100}));

	map.on('mousemove', (e) => {
		document.getElementById('info').innerHTML =
		// `e.point` is the x, y coordinates of the `mousemove` event
		// relative to the top-left corner of the map.
		JSON.stringify(e.point) +
		'<br />' +
		// `e.lngLat` is the longitude, latitude geographical position of the event.
		JSON.stringify(e.lngLat.wrap());
	});

	const lng = document.getElementById('id_longitude');
	const lat = document.getElementById('id_latitude');

	var marker = new mapboxgl.Marker().setLngLat([lng.value, lat.value]).addTo(map);

	function add_marker (e) {
		var coordinates = e.lngLat;
		lng.value = coordinates.lng;
		lat.value = coordinates.lat;
		console.log('Lng:', coordinates.lng, 'Lat:', coordinates.lat);
		marker.setLngLat(coordinates).addTo(map);

	}

	map.on('click', add_marker);

</script>

{% endblock content %}